### ISSUE TITLE
Scientific evidence of the algorithm missing

### ISSUE THREAD

**Issue by MbBrainz** [gbossi/BitcoinClusterAggregator#2]
Hi there, 
I was wondering if there is any scientific backup for the algorithm u are using to match the addresses of the same owner? Can you provide a comparison to other ways of doing that? A speed analysis for example?

**Comment by gbossi** [comment]
Hi, 
The questions you are asking are very general. The algorithm is briefly explained in the README.md file. 
Regarding the comparison with other algorithms, it is not easy to give an answer. This repo contains a distributed solution, so it cannot be compared with other solutions that are not distributed. An upper bound on the time complexity is O(N2), with N as the number of transactions. However, since it is based on the Bitcoin Blockchain, the average complexity is closer to O(NlogN), due to the shape of the transactions graph.
